[package]
name = "octo_chess"
version = "0.2.0"
edition = "2021"

[[debug]]
name = "octo_chess_debug"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = "0.20.2"
fixed_trigonometry = "0.3.5"