[package]
name = "octo_chess"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = {version = "0.20.2", feature = ["mint"] }
fixed_trigonometry = "0.3.5"
aseprite = "0.1.3"
serde_json = "1.0.85"